 services:
     app:
       build:
         context: .
         dockerfile: Dockerfile
       ports:
         - "8000:80"
       depends_on:
         - db
       environment:
         - DB_HOST=db
         - DB_PORT=3306
         - DB_DATABASE=laravel
         - DB_USERNAME=root
         - DB_PASSWORD=root

     db:
       image: mysql:5.7
       environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: laravel
       ports:
         - "3306:3306"